```{r}
getwd()
#setwd("~/EastmanLamPark_ENV872_EDA_FinalProject")
library(tidyverse)
library(dplyr)

header <- scan ("./Raw_Data/WaterTempData/Beaufort/beaufort_2010.csv", nlines = 1,sep=",", what =character())

beaufort11 = read.csv( "./Raw_Data/WaterTempData/Beaufort/beaufort_2011.csv",sep = ",", header = F, skip=2)
beaufort12 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2012.csv",sep = ",", header = F, skip=2)
beaufort13 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2013.csv",sep = ",", header = F, skip=2)
beaufort14 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2014.csv",sep = ",", header = F, skip=2) 
beaufort15 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2015.csv",sep = ",", header = F, skip=2)
beaufort16 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2016.csv",sep = ",", header = F, skip=2)
beaufort17 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2017.csv",sep = ",", header = F, skip=2)
beaufort18 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2018.csv",sep = ",", header = F, skip=2)
beaufort19 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2019.csv",sep = ",", header = F, skip=2)
beaufort20 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2020.csv",sep = ",", header = F, skip=2)
beaufort21 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2021.csv",sep = ",", header = F, skip=2)

beaufort <-rbind(beaufort11,beaufort12,beaufort13,beaufort14,beaufort15, beaufort16, beaufort17, beaufort18, beaufort19, beaufort20,beaufort21)
names (beaufort) <- header


```

```{r}
#because there is an error in the data (random 999 was in between wtmp data
#so made all data NA for all random 999 and replaced that to the next avilable data point 
library(zoo)
beaufort <- beaufort %>% 
  mutate (WTMP=ifelse(WTMP ==999,NA,WTMP)) %>% 
  #mutate(WTMP =na.locf(WTMP), fromLast =T)
  mutate(WTMP = zoo::na.approx(WTMP))


beaufort_wtmp <- beaufort %>% 
  select("#YY","MM","DD","WTMP") %>% 
  dplyr::rename (Year = "#YY", Month = "MM", Day ="DD")

beaufort_daily_wtmp <-  beaufort_wtmp %>% 
 dplyr::group_by( Year, Month, Day) %>% 
 dplyr::summarise(dailywtmp = mean(WTMP),.groups ='drop')

beaufort_monthly_wtmp <- beaufort_wtmp %>% 
  dplyr::group_by(Year, Month) %>% 
  dplyr::summarise( monthlywtmp = mean(WTMP), .groups ='drop')
```

```{r}
#exporting data into csv

#write.csv(beaufort_daily_wtmp, file= "C:/Users/hyjgp/Documents/EastmanLamPark_ENV872_EDA_FinalProject/Processed_Data/Beaufort_daily_wtmp.csv",row.names =FALSE)
write.csv(beaufort_daily_wtmp, 'daily_beaufort_wtmp.csv')

#write.csv(beaufort_monthly_wtmp, file= "C:/Users/hyjgp/Documents/EastmanLamPark_ENV872_EDA_FinalProject/Processed_Data/Beaufort_monthly_wtmp.csv",row.names =FALSE)
write.csv(beaufort_monthly_wtmp, 'monthly_beaufort_wtmp.csv')


```

