```{r}
getwd()
library(tidyverse)
library(dplyr)

header <- scan ("./Raw_Data/WaterTempData/Hatteras/hatteras_2010.csv", nlines = 1,sep=",", what =character())

Hatteras11 = read.csv( "./Raw_Data/WaterTempData/Hatteras/hatteras_2011.csv",sep = ",", header = F, skip=2)
Hatteras12 = read.csv("./Raw_Data/WaterTempData/Hatteras/hatteras_2012.csv",sep = ",", header = F, skip=2)
Hatteras13 = read.csv("./Raw_Data/WaterTempData/Hatteras/hatteras_2013.csv",sep = ",", header = F, skip=2)
Hatteras14 = read.csv("./Raw_Data/WaterTempData/Hatteras/hatteras_2014.csv",sep = ",", header = F, skip=2) 
Hatteras15 = read.csv("./Raw_Data/WaterTempData/Hatteras/hatteras_2015.csv",sep = ",", header = F, skip=2)
Hatteras16 = read.csv("./Raw_Data/WaterTempData/Hatteras/hatteras_2016.csv",sep = ",", header = F, skip=2)
Hatteras17 = read.csv("./Raw_Data/WaterTempData/Hatteras/hatteras_2017.csv",sep = ",", header = F, skip=2)
Hatteras18 = read.csv("./Raw_Data/WaterTempData/Hatteras/hatteras_2018.csv",sep = ",", header = F, skip=2)
Hatteras19 = read.csv("./Raw_Data/WaterTempData/Hatteras/hatteras_2019.csv",sep = ",", header = F, skip=2)
Hatteras20 = read.csv("./Raw_Data/WaterTempData/Hatteras/hatteras_2020.csv",sep = ",", header = F, skip=2)
Hatteras21 = read.csv("./Raw_Data/WaterTempData/Hatteras/hatteras_2021.csv",sep = ",", header = F, skip=2)

Hatteras <-rbind(Hatteras11,Hatteras12,Hatteras13,Hatteras14,Hatteras15, Hatteras16, Hatteras17, Hatteras18, Hatteras19, Hatteras20,Hatteras21)
names (Hatteras) <- header


```

```{r}
#because there is an error in the data (random 999 was in between wtmp data
#so made all data NA for all random 999 and replaced that to the next avilable data point 
library(zoo)
Hatteras <- Hatteras %>% 
  mutate (WTMP=ifelse(WTMP ==999,NA,WTMP)) %>% 
  mutate(WTMP = zoo::na.approx(WTMP))
  ##mutate(WTMP =na.locf(WTMP), fromLast =T)

Hatteras_wtmp <- Hatteras %>% 
  select("#YY","MM","DD","WTMP") %>% 
  dplyr::rename (Year = "#YY", Month = "MM", Day ="DD")

Hatteras_daily_wtmp <-  Hatteras_wtmp %>% 
 dplyr:: group_by( Year, Month, Day) %>% 
 dplyr::summarise(dailywtmp = mean(WTMP),.groups ='drop')

Hatteras_monthly_wtmp <- Hatteras_wtmp %>% 
 dplyr:: group_by(Year, Month) %>% 
 dplyr::summarise( monthlywtmp = mean(WTMP), .groups ='drop')
```

```{r}
#exporting data into csv

#write.csv(Hatteras_daily_wtmp, file= "C:/Users/hyjgp/Documents/EastmanLamPark_ENV872_EDA_FinalProject/Processed_Data/Hatteras_daily_wtmp.csv",row.names =FALSE)
getwd()
write.csv(Hatteras_daily_wtmp, 'daily_hatteras_wtmp.csv')

#write.csv(Hatteras_monthly_wtmp, file= "C:/Users/hyjgp/Documents/EastmanLamPark_ENV872_EDA_FinalProject/Processed_Data/Hatteras_monthly_wtmp.csv",row.names =FALSE)
write.csv(Hatteras_daily_wtmp, 'monthly_hatteras_wtmp.csv')

```
