```{r}
getwd()
library(tidyverse)
library(dplyr)
```


```{r}
header <- scan ("./Raw_Data/WaterTempData/Wrightsville/wrightsville_2010.csv", nlines = 1,sep=",", what =character())

Wrightsville11 = read.csv( "./Raw_Data/WaterTempData/Wrightsville/wrightsville_2011.csv",sep = ",", header = F, skip=2)
Wrightsville12 = read.csv("./Raw_Data/WaterTempData/Wrightsville/wrightsville_2012.csv",sep = ",", header = F, skip=2)
Wrightsville13 = read.csv("./Raw_Data/WaterTempData/Wrightsville/wrightsville_2013.csv",sep = ",", header = F, skip=2)
Wrightsville14 = read.csv("./Raw_Data/WaterTempData/Wrightsville/wrightsville_2014.csv",sep = ",", header = F, skip=2) 
Wrightsville15 = read.csv("./Raw_Data/WaterTempData/Wrightsville/wrightsville_2015.csv",sep = ",", header = F, skip=2)
Wrightsville16 = read.csv("./Raw_Data/WaterTempData/Wrightsville/wrightsville_2016.csv",sep = ",", header = F, skip=2)
Wrightsville17 = read.csv("./Raw_Data/WaterTempData/Wrightsville/wrightsville_2017.csv",sep = ",", header = F, skip=2)
Wrightsville18 = read.csv("./Raw_Data/WaterTempData/Wrightsville/wrightsville_2018.csv",sep = ",", header = F, skip=2)
Wrightsville19 = read.csv("./Raw_Data/WaterTempData/Wrightsville/wrightsville_2019.csv",sep = ",", header = F, skip=2)
Wrightsville20 = read.csv("./Raw_Data/WaterTempData/Wrightsville/wrightsville_2020.csv",sep = ",", header = F, skip=2)
Wrightsville21 = read.csv("./Raw_Data/WaterTempData/Wrightsville/wrightsville_2021.csv",sep = ",", header = F, skip=2)

Wrightsville <-rbind(Wrightsville11,Wrightsville12,Wrightsville13,Wrightsville14,Wrightsville15, Wrightsville16, Wrightsville17, Wrightsville18, Wrightsville19, Wrightsville20,Wrightsville21)
names (Wrightsville) <- header

```

```{r}
#because there is an error in the data (random 999 was in between wtmp data
#so made all data NA for all random 999 and replaced that to the next avilable data point 
library(zoo)
Wrightsville <- Wrightsville %>% 
  mutate (WTMP=ifelse(WTMP ==999,NA,WTMP)) %>% 
  mutate(WTMP =na.locf(WTMP), fromLast =T)

Wrightsville_wtmp <- Wrightsville %>% 
  select("#YY","MM","DD","WTMP") %>% 
  dplyr::rename (Year = "#YY", Month = "MM", Day ="DD")

Wrightsville_daily_wtmp <-  Wrightsville_wtmp %>% 
  dplyr::group_by(Year, Month, Day) %>% 
  dplyr::summarise(dailywtmp = mean(WTMP),.groups ='drop')

Wrightsville_monthly_wtmp <- Wrightsville_wtmp %>% 
  dplyr::group_by(Year, Month) %>% 
  dplyr::summarise( monthlywtmp = mean(WTMP), .groups ='drop')
```

```{r}

write.csv(Wrightsville_daily_wtmp, file= "C:/Users/hyjgp/Documents/EastmanLamPark_ENV872_EDA_FinalProject/Processed_Data/Wrightsville_daily_wtmp.csv",row.names =FALSE)

write.csv(Wrightsville_monthly_wtmp, file= "C:/Users/hyjgp/Documents/EastmanLamPark_ENV872_EDA_FinalProject/Processed_Data/Wrightsville_monthly_wtmp.csv",row.names =FALSE)
```

