```{r}
#Set working directory and load in libraries
#setwd("~/EastmanLamPark_ENV872_EDA_FinalProject")
getwd()

library(tidyverse)
library(dplyr)
library(plyr)
library(lubridate)
library(stringr)
library(readr)
library(ggplot2)
#install.packages("gridExtra")
library(gridExtra)
```

```{r}
#Import data
combined_sea_level_data <- read.csv("./Data/Processed_Data/combine_sealevel.csv")
#Add month-year column from date
combined_sea_level_data$Date<- as.Date(combined_sea_level_data$Date)
  
mytheme <- theme_classic(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")
theme_set(mytheme)
```

```{r, fig.cap="Sea Level Trend Exploration", fig.align='left', fig.height= 2.5}
#Exploring sea level measurements over the 12 years

sea_level_plot <- ggplot(combined_sea_level_data, aes(x=Date, y=MSL..ft., group = Station))+geom_line(aes(color = Station)) + geom_smooth(method= "lm", se=FALSE) +
    labs(title = "Mean Sea Levels (2010-2022)",
        y = "Mean Sea Level (ft)", x = "Date (Month-Year)") + 
  scale_x_date(date_breaks="18 months", date_labels ="%b-%y")
print(sea_level_plot)

tide_level <- ggplot(combined_sea_level_data, aes(x=Date, y=MTL..ft., group = Station))+geom_line(aes(color = Station)) +
    labs(title = "Mean Tide Levels (2010-2022)",
        y = "Mean Tide (ft) Level", x = "Date")
print(tide_level)



#Sea Level Measurements for 2011 and 2021

sea_level_2011 <- ggplot(combined_sea_level_data, aes(x=Date, y=MSL..ft., group = Station))+geom_line(aes(color = Station)) + geom_smooth(method= "lm", se=FALSE) +
    labs(title = "Mean Sea Levels (2011)",
        y = "Mean Sea Level (ft)", x = "Date (Month-Year)") +
  scale_x_date(limits= as.Date(c("2011-01-01", "2011-12-01")), date_breaks="2 months", date_labels ="%b-%y")
print(sea_level_2011)

sea_level_2021 <- ggplot(combined_sea_level_data, aes(x=Date, y=MSL..ft., group = Station))+geom_line(aes(color = Station)) + geom_smooth(method= "lm", se=FALSE) +
    labs(title = "Mean Sea Levels (2011)",
        y = "Mean Sea Level (ft)", x = "Date (Month-Year)") +
  scale_x_date(limits= as.Date(c("2021-01-01", "2021-12-01")), date_breaks="2 months", date_labels ="%b-%y")
print(sea_level_2021)

combined_2011_2021<- grid.arrange(sea_level_2011, sea_level_2021, ncol= 2, common.ledgend= TRUE)
print(combined_2011_2021)
```

```{r, fig.cap="Water Temperature Trend Exploration", fig.align='left', fig.height= 2.5}
#Exploring Trends in Water Temperature

#Daily Water Temperature Measurements for 2011-2022
combined_daily_wtmp_data <- read.csv("./Data/Processed_Data/combine_daily_water_temp.csv")
combined_daily_wtmp_data$Date<-as.Date(combined_daily_wtmp_data$Date, format = "%Y-%m-%d")
daily_wtmp_level_plot <-ggplot(combined_daily_wtmp_data, aes(x =Date, y=dailywtmp,group= Station))+
  geom_line(aes(color=Station))+
  labs(title = "Daily Water Temperature (2011-2022)", y= "Daily Water Temp (Celcius)", x= "Date")+
  scale_x_date(date_breaks = "6 months", date_labels = "%Y-%m-%d")+
  theme(axis.text.x = element_text(angle=60, hjust=1))
print(daily_wtmp_level_plot)

#Monthly Water Temperature Measurements for 2011-2022
combined_monthly_wtmp_data <- read.csv("./Data/Processed_Data/combine_monthly_water_temp.csv")
combined_monthly_wtmp_data$Date<-as.Date(combined_monthly_wtmp_data$Date, format = "%Y-%m-%d")
monthly_wtmp_level_plot <-ggplot(combined_monthly_wtmp_data, aes(x =Date, y=monthlywtmp,group= Station))+
  geom_line(aes(color=Station))+
  labs(title = "Monthly Water Temperature (2011-2022)", y= "Monthly Water Temp (Celcius)", x= "Date")+
  scale_x_date(date_breaks = "6 months", date_labels = "%Y-%m")+
  theme(axis.text.x = element_text(angle=60, hjust=1))
print(monthly_wtmp_level_plot)

```

