```{r set-up, include = FALSE}
#Setting working directory
#setwd("/Users/ariellam/Desktop/EDA-Fall2022/EastmanLamPark_ENV872_EDA_FinalProject/EastmanLamPark_ENV872_EDA_FinalProject")
getwd()

#setwd("~/EastmanLamPark_ENV872_EDA_FinalProject")


#Load Packages
library(tidyverse)
library(dplyr)
#install.packages("plyr")
library(plyr)
library(lubridate)
library(stringr)
library(readr)

#Import Beaufort datasets
Beaufort_SeaLevel <- read_csv("Raw_Data/SeaLevelData/Beaufort_Marine_Lab_2010_2022_SeaLevelRise.csv")

header <- scan ("./Raw_Data/WaterTempData/Beaufort/beaufort_2010.csv", nlines = 1,sep=",", what =character())
beaufort10 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2010.csv",sep = ",", header = F, skip=2)
beaufort11 = read.csv( "./Raw_Data/WaterTempData/Beaufort/beaufort_2011.csv",sep = ",", header = F, skip=2)
beaufort12 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2012.csv",sep = ",", header = F, skip=2)
beaufort13 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2013.csv",sep = ",", header = F, skip=2)
beaufort14 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2014.csv",sep = ",", header = F, skip=2) 
beaufort15 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2015.csv",sep = ",", header = F, skip=2)
beaufort16 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2016.csv",sep = ",", header = F, skip=2)
beaufort17 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2017.csv",sep = ",", header = F, skip=2)
beaufort18 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2018.csv",sep = ",", header = F, skip=2)
beaufort19 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2019.csv",sep = ",", header = F, skip=2)
beaufort20 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2020.csv",sep = ",", header = F, skip=2)
beaufort21 = read.csv("./Raw_Data/WaterTempData/Beaufort/beaufort_2021.csv",sep = ",", header = F, skip=2)

#Import Hatteras Datasets
Hatteras_SeaLevel<- read_csv("Raw_Data/SeaLevelData/Hatteras_2010_2022_SeaLevelRise.csv")

header <- scan ("./Raw_Data/WaterTempData/Hatteras/Hatteras_2010.csv", nlines = 1,sep=",", what =character())
Hatteras10 = read.csv("./Raw_Data/WaterTempData/Hatteras/Hatteras_2010.csv",sep = ",", header = F, skip=2)
Hatteras11 = read.csv( "./Raw_Data/WaterTempData/Hatteras/Hatteras_2011.csv",sep = ",", header = F, skip=2)
Hatteras12 = read.csv("./Raw_Data/WaterTempData/Hatteras/Hatteras_2012.csv",sep = ",", header = F, skip=2)
Hatteras13 = read.csv("./Raw_Data/WaterTempData/Hatteras/Hatteras_2013.csv",sep = ",", header = F, skip=2)
Hatteras14 = read.csv("./Raw_Data/WaterTempData/Hatteras/Hatteras_2014.csv",sep = ",", header = F, skip=2) 
Hatteras15 = read.csv("./Raw_Data/WaterTempData/Hatteras/Hatteras_2015.csv",sep = ",", header = F, skip=2)
Hatteras16 = read.csv("./Raw_Data/WaterTempData/Hatteras/Hatteras_2016.csv",sep = ",", header = F, skip=2)
Hatteras17 = read.csv("./Raw_Data/WaterTempData/Hatteras/Hatteras_2017.csv",sep = ",", header = F, skip=2)
Hatteras18 = read.csv("./Raw_Data/WaterTempData/Hatteras/Hatteras_2018.csv",sep = ",", header = F, skip=2)
Hatteras19 = read.csv("./Raw_Data/WaterTempData/Hatteras/Hatteras_2019.csv",sep = ",", header = F, skip=2)
Hatteras20 = read.csv("./Raw_Data/WaterTempData/Hatteras/Hatteras_2020.csv",sep = ",", header = F, skip=2)
Hatteras21 = read.csv("./Raw_Data/WaterTempData/Hatteras/Hatteras_2021.csv",sep = ",", header = F, skip=2)

#Import Wrightsville Datasets
Wrightsville_SeaLevel<- read_csv("Raw_Data/SeaLevelData/WrightsvilleBeach_2010_2022_SeaLevelRise.csv")
header <- scan ("./Raw_Data/WaterTempData/Wrightsville/Wrightsville_2010.csv", nlines = 1,sep=",", what =character())
Wrightsville10 = read.csv("./Raw_Data/WaterTempData/Wrightsville/Wrightsville_2010.csv",sep = ",", header = F, skip=2)
Wrightsville11 = read.csv( "./Raw_Data/WaterTempData/Wrightsville/Wrightsville_2011.csv",sep = ",", header = F, skip=2)
Wrightsville12 = read.csv("./Raw_Data/WaterTempData/Wrightsville/Wrightsville_2012.csv",sep = ",", header = F, skip=2)
Wrightsville13 = read.csv("./Raw_Data/WaterTempData/Wrightsville/Wrightsville_2013.csv",sep = ",", header = F, skip=2)
Wrightsville14 = read.csv("./Raw_Data/WaterTempData/Wrightsville/Wrightsville_2014.csv",sep = ",", header = F, skip=2) 
Wrightsville15 = read.csv("./Raw_Data/WaterTempData/Wrightsville/Wrightsville_2015.csv",sep = ",", header = F, skip=2)
Wrightsville16 = read.csv("./Raw_Data/WaterTempData/Wrightsville/Wrightsville_2016.csv",sep = ",", header = F, skip=2)
Wrightsville17 = read.csv("./Raw_Data/WaterTempData/Wrightsville/Wrightsville_2017.csv",sep = ",", header = F, skip=2)
Wrightsville18 = read.csv("./Raw_Data/WaterTempData/Wrightsville/Wrightsville_2018.csv",sep = ",", header = F, skip=2)
Wrightsville19 = read.csv("./Raw_Data/WaterTempData/Wrightsville/Wrightsville_2019.csv",sep = ",", header = F, skip=2)
Wrightsville20 = read.csv("./Raw_Data/WaterTempData/Wrightsville/Wrightsville_2020.csv",sep = ",", header = F, skip=2)
Wrightsville21 = read.csv("./Raw_Data/WaterTempData/Wrightsville/Wrightsville_2021.csv",sep = ",", header = F, skip=2)

```

#Research Question: Do climate change indicators, sea level and water temperature have a statistically significant relationship at three coastal sites in North Carolina: Beaufort, Cape Hatteras, and Wrightsville Beach?
```{r}
#Wrangle data to combine the water temperature data for each year into one csv for each site
Beaufort.Water.Temp <-rbind(beaufort10,beaufort11,beaufort12,beaufort13,beaufort14,beaufort15, beaufort16, beaufort17, beaufort18, beaufort19, beaufort20,beaufort21)
names (Beaufort.Water.Temp) <- header

Hatteras.Water.Temp <-rbind(Hatteras10,Hatteras11,Hatteras12,Hatteras13,Hatteras14,Hatteras15, Hatteras16, Hatteras17, Hatteras18, Hatteras19, Hatteras20,Hatteras21)
names (Hatteras.Water.Temp) <- header

Wrightsville.Water.Temp <-rbind(Wrightsville10,Wrightsville11,Wrightsville12,Wrightsville13,Wrightsville14,Wrightsville15, Wrightsville16, Wrightsville17, Wrightsville18, Wrightsville19, Wrightsville20,Wrightsville21)
names (Wrightsville.Water.Temp) <- header

#Clean-up environment and remove the individual data frames for each year
```

```{r}
#Wrangle Beaufort water temperature data frames to be averaged by month
beaufort_wtmp <- Beaufort.Water.Temp %>% 
  select("#YY","MM","DD","WTMP") %>% 
  dplyr::rename(Year = "#YY", Month = "MM", Day ="DD")

beaufort_daily_wtmp <-  beaufort_wtmp %>% 
  group_by(Year, Month, Day) %>% 
  summarise(dailywtmp = mean(WTMP),.groups ='drop')

beaufort_monthly_wtmp <- beaufort_wtmp %>% 
  group_by(Year, Month) %>% 
  summarise( monthlywtmp = mean(WTMP), .groups ='drop')

#Wrangle Hatteras water temperature dataframe to be averaged by month
Hatteras_wtmp <- Hatteras.Water.Temp %>% 
  select("#YY","MM","DD","WTMP") %>% 
  dplyr::rename (Year = "#YY", Month = "MM", Day ="DD")

Hatteras_daily_wtmp <-  Hatteras_wtmp %>% 
  group_by( Year, Month, Day) %>% 
  summarise(dailywtmp = mean(WTMP),.groups ='drop')

Hatteras_monthly_wtmp <- Hatteras_wtmp %>% 
  group_by(Year, Month) %>% 
  summarise( monthlywtmp = mean(WTMP), .groups ='drop')



#Wrangle Wrightsville water temperature data frame to be averaged by month
Wrightsville_wtmp <- Wrightsville.Water.Temp %>% 
  select("#YY","MM","DD","WTMP") %>% 
  dplyr::rename (Year = "#YY", Month = "MM", Day ="DD")

Wrightsville_daily_wtmp <-  Wrightsville_wtmp %>% 
  group_by( Year, Month, Day) %>% 
  summarise(dailywtmp = mean(WTMP),.groups ='drop')

Wrightsville_monthly_wtmp <- Wrightsville_wtmp %>% 
  group_by(Year, Month) %>% 
  summarise( monthlywtmp = mean(WTMP), .groups ='drop')

#combine daily datasets for water temperature 

combine_daily_water_temp <- rbind (beaufort_daily_wtmp, Hatteras_daily_wtmp, Wrightsville_daily_wtmp)
write.csv(combine_daily_water_temp, 'combine_daily_water_temp.csv')

#combine daily datasets for water temperature 

combine_monthly_water_temp <- rbind (beaufort_monthly_wtmp, Hatteras_monthly_wtmp, Wrightsville_monthly_wtmp)
write.csv(combine_monthly_water_temp, 'combine_monthly_water_temp.csv')



```

```{r}
#clean-up sea level datasets
Beaufort_SeaLevel <- Beaufort_SeaLevel %>% select(c(1,6,7)) %>% mutate(Station= "Beaufort")
Hatteras_SeaLevel$Date <- as.Date(Hatteras_SeaLevel$Date, format = "%m/%d/%y")
Hatteras_SeaLevel <- Hatteras_SeaLevel %>% select(c(1,6,7)) %>% mutate(Station= "Hatteras")
Wrightsville_SeaLevel <-Wrightsville_SeaLevel %>% select(c(1,6,7)) %>% mutate(Station= "Wrightsville")

combine_sealevel <- rbind (Beaufort_SeaLevel, Hatteras_SeaLevel, Wrightsville_SeaLevel)
write.csv(combine_sealevel, 'combine_sealevel.csv')


```

```{r}
#combine and clean sea level temp datasets
getwd()
daily_hatteras_wtmp <- read.csv("daily_hatteras_wtmp.csv")
monthly_hatteras_wtmp <- read.csv("monthly_hatteras_wtmp.csv")

daily_beaufort_wtmp <- read.csv("daily_hatteras_wtmp.csv")
monthly_beaufort_wtmp <- read.csv("monthly_hatteras_wtmp.csv")

daily_Wrightsville_wtmp <- read.csv("daily_hatteras_wtmp.csv")
monthly_Wrightsville_wtmp <- read.csv("monthly_Wrightsville_wtmp.csv")


combine_daily_wtmp <- rbind (daily_hatteras_wtmp, daily_beaufort_wtmp, daily_Wrightsville_wtmp)
write.csv(combine_daily_wtmp, 'combine_daily_wtmp.csv')


combine_monthly_wtmp <- rbind (monthly_hatteras_wtmp, monthly_beaufort_wtmp, monthly_Wrightsville_wtmp)
write.csv(combine_monthly_wtmp, 'combine_monthly_wtmp.csv')

```